### ISSUE TITLE
Source in releases, not git

### ISSUE THREAD

**Issue by JJTech0130** [MinecraftMachina/McMouser#1]
Maybe you have a perfectly valid reason for this, but why is the source code distributed in a jar, as a release, rather then checked into git? It made me think that this mod was not open-source, and makes it harder to submit contributions.

**Comment by ViRb3** [comment]
It is not, check the branches ;)

**Comment by JJTech0130** [comment]
Ah, that makes sense. Perhaps a mention of that in the README to make it more clear?

**Comment by ViRb3** [comment]
Done!

**Comment by idkman2021** [comment]
what happens if i install this on windows

**Comment by ViRb3** [comment]
> what happens if i install this on windows

Nothing at all, the mod will be disabled.
