### ISSUE TITLE
still doesn't fix the bug where Mac inputs and looking around is broken

### ISSUE THREAD

**Issue by tissthecat** [MinecraftMachina/McMouser#12]
I'm using a MacBook Air M2 for Minecraft, and sometimes when things are slow and laggy, my mouse stutters when I look around. not only that, when I click to place or break or use the keys to move around, sometimes the inputs are delayed, where I tap w, and it doesn't do anything, so I tap it more times, it sticks and I have to press it again to stop, and sometimes even that won't work. this happens to all movement keys including jump and sneak. also the mouse thing usually happens when I hold the key down when it's lagging and look around to change directions. not a fault of your mod, but I think you should add a fix for that too. thanks in advance. :)

**Comment by ViRb3** [comment]
Is there even a fix for this? Sounds like your laptop is overloaded, maybe even overheating, and these are normal consequences from that.
