### ISSUE TITLE
ctrl (crouch) + spacebar (jump) doesn't work

### ISSUE THREAD

**Issue by H3nno** [MinecraftMachina/McMouser#2]
I cannot jump while crouching. 

Pressing control (crouch) and shift (sprint) at the same time -> jumping is possible while still in crouched stance.

McMouser v1.18.0-fabric-1.0.2. ManyMC (MultiMC fork), M1 Pro, ARM native Java

**Comment by ViRb3** [comment]
By default, control = sprint, and shift = crouch. In both cases though, holding control + shift and jumping work for me. This is likely a conflict with another macOS keybind that you have, check System Preferences > Keyboard > Shortcuts.

**Comment by H3nno** [comment]
You're absolutely right. 

Thanks for the quick response!

Shame on me for not testing properly.
